# Generated by Django 4.0.3 on 2022-12-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_salesrecord_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
