# Generated by Django 4.0.3 on 2022-12-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_salesrecord_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='sold',
        ),
    ]
