# Generated by Django 4.0.3 on 2022-12-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_automobilevo_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
    ]
