# Generated by Django 4.0.3 on 2022-12-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_alter_technician_employee_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceappointment",
            old_name="owner",
            new_name="customer_name",
        ),
    ]
