# Generated by Django 4.0.3 on 2022-12-15 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_remove_serviceappointment_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappointment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='VIN',
            field=models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)]),
        ),
    ]
